fail_fast: false
exclude: |
    (?x)^(
        tests/data/.*
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.7
    hooks:
      - id: pymarkdown
