site_name: docs.fullctl.com
site_url: https://docs.fullctl.com
repo_url: https://github.com/fullctl/docs.fullctl.com/

theme: readthedocs

nav:
  - Home: index.md
  - Definitions: Definitions.md
#  - PeerCtl:
  - IXCtl:
    - Share the Member List: ixctl/Share-the-member-list.md
  - PrefixCtl:
    - Definitions: PREFIXCLT/PeerCtl-Definitions.md
    - Add Prefix Set: PREFIXCLT/Add-Prefix-Set.md
    - Settings: PREFIXCLT/Settings.md
    - Add Monitor: PREFIXCLT/Add-Monitor.md
    - Check Reputation: PREFIXCLT/Check-Reputation.md
    - API: PREFIXCLT/API.md
  - How Tos:
    - Sign up for FullCtl: HowTos/Sign-up-for-account.md
    - Sign up for PeeringDB: HowTos/Sign-up-for-PeeringDB.md
    - Login and Update Settings: HowTos/LogIn.md
    - Add Organization: HowTos/Add-Organization.md
    - Add Users: HowTos/Add-Users.md
