site_name: docs.fullctl.com
site_url: https://docs.fullctl.com
repo_url: https://github.com/fullctl/docs.fullctl.com/

theme: readthedocs

nav:
  - Home: index.md
  - Definitions: Definitions.md
  - How Tos:
    - Sign up for FullCtl: HowTos/Sign-up-for-account.md
    - Sign up for PeeringDB: HowTos/Sign-up-for-PeeringDB.md
    - Login and Update Settings: HowTos/LogIn.md
    - Add Organization: HowTos/Add-Organization.md
    - Add Users: HowTos/Add-Users.md
  - aclCtl:
    - Add a Rule: aclCtl/Add-a-Rule.md
    - Prioritize Rules: aclCtl/Prioritize-Rules.md
    - Custom Templates: aclCtl/Custom-Templates.md
  - IXCtl:
    - Share the Member List: ixctl/Share-the-member-list.md
  - PrefixCtl:
    - Definitions: prefixctl/PrefixCtl-Definitions.md
    - Add Prefix Set: prefixctl/Add-Prefix-Set.md
    - Settings: prefixctl/Settings.md
    - Add Monitor: prefixctl/Add-Monitor.md
    - Check Reputation: prefixctl/Check-Reputation.md
    - API: prefixctl/API.md
