site_name: docs.fullctl.com
site_url: https://docs.fullctl.com
repo_url: https://github.com/fullctl/docs.fullctl.com/

theme: readthedocs

nav:
  - Home: index.md
  - Definitions: Definitions.md
  - aaaCtl:
    - Sign up for FullCtl: aaaCtl/Sign-up-for-account.md
    - Sign up for PeeringDB: aaaCtl/Sign-up-for-PeeringDB.md
    - Login and Update Settings: aaaCtl/LogIn.md
    - Add Organization: aaaCtl/Add-Organization.md
    - Add Users: aaaCtl/Add-Users.md
  - aclCtl:
    - Access Control List: aclCtl/Access-Control-List.md
    - Add a Rule: aclCtl/Add-a-Rule.md
    - Prioritize Rules: aclCtl/Prioritize-Rules.md
    - Custom Templates: aclCtl/Custom-Templates.md
  - IXCtl:
    - Share the Member List: ixctl/Share-the-member-list.md
  - PeerCtl:
    - Definitions: PEERCTL/PeerCtl-Definitions.md
    - Summary: PEERCTL/Summary.md
    - Settings: PEERCTL/Settings.md
    - Add/Remove Connections: PEERCTL/AddRemove-Connections.md
    - Set MD5 Password: PEERCTL/Set-MD5-Password.md
    - Set Policy: PEERCTL/Set-Policy.md
    - Device Configuration: PEERCTL/Device-Configuration.md
    - Request Peering: PEERCTL/Request-Peering.md
  - PrefixCtl:
    - Definitions: prefixctl/PrefixCtl-Definitions.md
    - Add Prefix Set: prefixctl/Add-Prefix-Set.md
    - Settings: prefixctl/Settings.md
    - Add Monitor: prefixctl/Add-Monitor.md
    - Check Reputation: prefixctl/Check-Reputation.md
    - API: prefixctl/API.md
