site_name: docs.fullctl.com
site_url: https://docs.fullctl.com
repo_url: https://github.com/fullctl/docs.fullctl.com/

theme: readthedocs

nav:
  - Home: index.md
  - Definitions: definitions.md
  - PeerCtl:
  - IXCtl:
    - Share the Member List: ixctl/Share-the-member-list.md
  - PrefixCtl:
  - How Tos:
    - Sign up for FullCtl: howto/Sign-up-for-account.md
    - Sign up for PeeringDB: howto/Sign-up-for-PeeringDB.md
    - Login: howto/Login.md
    - Add Organization: howto/Add-Organization.md
    - Add Users: howto/Add-Users.md
