site_name: docs.fullctl.com
site_url: https://docs.fullctl.com
repo_url: https://github.com/fullctl/docs.fullctl.com/

theme: readthedocs

nav:
  - Home: index.md
  - Definitions: Definitions.md
  - aaaCtl:
    - Sign up for FullCtl: aaaCtl/Sign-up-for-account.md
    - Sign up for PeeringDB: aaaCtl/Sign-up-for-PeeringDB.md
    - Login and Update Settings: aaaCtl/LogIn.md
    - Add Organization: aaaCtl/Add-Organization.md
    - Add Users: aaaCtl/Add-Users.md
  - aclCtl:
    - Access Control List: aclCtl/Access-Control-List.md
    - Add a Rule: aclCtl/Add-a-Rule.md
    - Prioritize Rules: aclCtl/Prioritize-Rules.md
    - Custom Templates: aclCtl/Custom-Templates.md
  - IXCtl:
    - Import an IX: ixctl/Import-an-IX.md
    - Create an IX: ixctl/Create-an-IX.md
    - Add a Memeber: ixctl/Add-a-Member.md
    - Share the Member List: ixctl/Share-the-member-list.md
    - Add Routeserver: ixctl/Add-Routeserver.md
    - Delete Exchange: ixctl/Delete-Exchange.md
  - PeerCtl:
    - Definitions: PeerCtl/PeerCtl-Definitions.md
    - Summary: PeerCtl/Summary.md
    - Settings: PeerCtl/Settings.md
    - Add/Remove Connections: PeerCtl/AddRemove-Connections.md
    - Set MD5 Password: PeerCtl/Set-MD5-Password.md
    - Set Policy: PeerCtl/Set-Policy.md
    - Device Configuration: PeerCtl/Device-Configuration.md
    - Request Peering: PeerCtl/Request-Peering.md
  - PrefixCtl:
    - Definitions: prefixctl/PrefixCtl-Definitions.md
    - Add Prefix Set: prefixctl/Add-Prefix-Set.md
    - Settings: prefixctl/Settings.md
    - Add Monitor: prefixctl/Add-Monitor.md
    - Check Reputation: prefixctl/Check-Reputation.md
    - API: prefixctl/API.md
  - DeviceCtl:
    - Add Facility: DeviceCtl/Add-Facility.md
    - Add Device: DeviceCtl/Add-Device.md
    - Ports: DeviceCtl/Ports.md
