site_name: docs.fullctl.com
site_url: https://docs.fullctl.com
repo_url: https://github.com/fullctl/docs.fullctl.com/
form_url: "https://account.fullctl.io/api/account/contact"

extra_css:
  - extra/extra.css
  - extra/header.css
  - extra/footer.css

extra_javascript:
  - extra/js/twentyc/twentyc.core.min.js
  - extra/js/twentyc/twentyc.rest.js
  - extra/js/app.js
  - extra/js/extra.js

theme:
  main_site: https://www.fullctl.com
  favicon: extra/assets/favicon.ico
  name: material
  palette:
    primary: "#191F26"
    accent: "#D1FF27"
  font:
    text: Archivo
  logo: extra/assets/FullCTL-Logo-LightBG.svg
  custom_dir: custom_theme/
  features:
    - navigation.expand

nav:
  - Home: 
    - Home: index.md
    - Components: Components.md
    - Definitions: Definitions.md
    - aaaCtl:
      - Sign up for FullCtl: aaaCtl/Sign-up-for-fullctl.md
      - Sign up for PeeringDB: aaaCtl/Sign-up-for-PeeringDB.md
      - Login and Update Settings: aaaCtl/LogIn-Update-Settings.md
      - Add Organization: aaaCtl/Add-Organization.md
      - Add Users: aaaCtl/Add-Users.md
      - User Privileges: aaaCtl/User-Privileges.md
    - aclCtl:
      - Access Control List: aclCtl/Access-Control-List.md
      - Add a Rule: aclCtl/Add-a-Rule.md
      - Prioritize Rules: aclCtl/Prioritize-Rules.md
      - Custom Templates: aclCtl/Custom-Templates.md
    - ixCtl:
      - Verify Exchange: ixctl/Verify-Exchange.md
      - Import an IX: ixctl/Import-an-IX.md
      - Create an IX: ixctl/Create-an-IX.md
      - Add a Member: ixctl/Add-a-Member.md
      - Share the Member List: ixctl/Share-the-member-list.md
      - Add a Route Server: ixctl/Add-A-Routeserver.md
      - Delete Exchange: ixctl/Delete-Exchange.md
    - PeerCtl:
      - Definitions: PeerCtl/PeerCtl-Definitions.md
      - Summary: PeerCtl/Summary.md
      - Add Peering Session: PeerCtl/Add-Peering-Session.md
      - Peering Settings: PeerCtl/Peering-Settings.md
      - Add/Remove Network Connection: PeerCtl/AddRemove-Network-Connection.md
      - Set MD5 Password: PeerCtl/Set-MD5-Password.md
      - Set Policy & Device Type: PeerCtl/Set-Policy-Device-Type.md
      - Templates: PeerCtl/Templates.md
      - Request Peering Option 1: PeerCtl/Request-Peering-1.md
      - Request Peering Option 2: PeerCtl/Request-Peering-2.md
      - Custom Email Templates: PeerCtl/Custom-Email-Templates.md
      - Peering Process: PeerCtl/Peering-Process.md
      - Device Configuration: PeerCtl/Device-Configuration.md
    - PrefixCtl:
      - Definitions: prefixctl/PrefixCtl-Definitions.md
      - Add Prefix Set: prefixctl/Add-Prefix-Set.md
      - Settings: prefixctl/Settings.md
      - Check Reputation: prefixctl/Check-Reputation.md
      - Add Monitor: prefixctl/Add-Monitor.md
      - Add ASN: prefixctl/Add-ASN.md
      - API: prefixctl/API.md
    - DeviceCtl:
      - Definitions: DeviceCtl/Definitions.md
      - Add Facility: DeviceCtl/Add-Facility.md
      - Add Device: DeviceCtl/Add-Device.md
      - Dashboard: DeviceCtl/Dashboard.md
      - Ports: DeviceCtl/Ports.md
  - IX Administrators Guide:
    - Overview: IX Admin Guide/Overview.md
    - Requirements: IX Admin Guide/Prereq-Req.md
    - Initial Setup: IX Admin Guide/Setting-up-Org.md
    - Setting up Services: IX Admin Guide/Setting-up-Services.md
    - Troubleshooting: IX Admin Guide/Troubleshooting.md
