name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Push to cloudflare-pages branch
        run: |
          git fetch --unshallow
          git checkout -B cloudflare-pages && git push --set-upstream origin cloudflare-pages --force

